### PR TITLE
Build system fixes

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -139,10 +139,10 @@ script:
         - echo "Checking linking and run from install..."
         - pushd $HOME
         - echo "Dynamic link.."
-        - ${CC} ${CFLAGS} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst_dynamic `PKG_CONFIG_PATH=${HOME}/odp-install/lib/pkgconfig:${PKG_CONFIG_PATH} pkg-config --cflags --libs libodp-dpdk`
+        - ${CC} ${CFLAGS} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst_dynamic `PKG_CONFIG_PATH=${HOME}/odp-install/lib/pkgconfig:${PKG_CONFIG_PATH} pkg-config --cflags --libs libodp-linux`
```
Comment (Bill-Fischofer-Linaro) [inline .travis.yml]: How does this work if both odp-linux and odp-dpdk are installed on the same system? I assume the idea is that they both install as libodp-linux and path selectors are used to pick which one but that applications should always link with libodp-linux?

Comment (lumag) [reply .travis.yml]: Yes. Basically ABI-compatible libraries should be interchangeable at runtime

Comment (matiaselo) [reply .travis.yml]: Is changing the library name necessary? IMHO from application point of view it would be clearer that different ODP implementations use distinct library names. How about if a user would like to install both implementations to the standard install path?

**Comment by matiaselo** [comment]
This patch set breaks build on my server (Ubuntu 16.04, GCC 5.4.0, DPDK 17.11).

```
CC       ../linux-generic/odp_rwlock_recursive.lo
In file included from /home/nnn/dev/dpdk.git/lib/librte_eal/common/include/rte_lcore.h:44:0,
                 from /home/nnn/dev/dpdk.git/lib/librte_eal/common/include/generic/rte_spinlock.h:50,
                 from /home/nnn/dev/dpdk.git/x86_64-native-linuxapp-gcc/include/rte_spinlock.h:41,
                 from /home/nnn/dev/dpdk.git/lib/librte_mempool/rte_mempool.h:72,
                 from /home/nnn/dev/dpdk.git/lib/librte_mbuf/rte_mbuf.h:65,
                 from ../../platform/linux-dpdk/include/odp/api/plat/packet_inlines.h:34,
                 from ../../platform/linux-dpdk/include/odp/api/plat/packet_flag_inlines.h:21,
                 from odp_packet_flags.c:7:
/home/matelo/dev/dpdk.git/lib/librte_eal/common/include/rte_eal.h:87:35: error: \u2018RTE_MAX_LCORE\u2019 undeclared here (not in a function)
  enum rte_lcore_role_t lcore_role[RTE_MAX_LCORE]; /**< State of cores. */
...
```

I assume this happens because some dpdk headers are included without first including rte_config.h. This same problem is in at least packet_inlines.h, odp_buffer_internal.h and odp_time.c.

**Comment by matiaselo** [comment]
README.DPDK should be updated to reflect the new supported DPDK version.

File: .travis.yml (hunk 1 above)
Comment (lumag) [reply .travis.yml]: @matiaselo From my point of view, all ABI-compatible libraries should have the same name, so that an application linked against one of them can be used with another (arch-optimized) one. E.g. an app compiled against linux-generic can be used with odp-dpdk library with no additional changes.

**Comment by lumag** [comment]
@matiaselo updated PR to include `rte_config.h` and to mention v17.11 in README.DPDK.

**Comment by matiaselo** [comment]
The rte_config.h include problem still persists when abi-compat is disabled.

```
./bootstrap
./configure --with-dpdk-path=/home/nnn/dev/dpdk.git/x86_64-native-linuxapp-gcc --disable-abi-compat
make
...
  CC       linux/thread.lo
In file included from /home/nnn/dev/dpdk.git/lib/librte_eal/common/include/rte_lcore.h:44:0,
                 from /home/nnn/dev/dpdk.git/lib/librte_eal/common/include/generic/rte_spinlock.h:50,
                 from /home/nnn/dev/dpdk.git/x86_64-native-linuxapp-gcc/include/rte_spinlock.h:41,
                 from /home/nnn/dev/dpdk.git/lib/librte_mempool/rte_mempool.h:72,
                 from /home/nnn/dev/dpdk.git/lib/librte_mbuf/rte_mbuf.h:65,
                 from ../platform/linux-dpdk/include/odp/api/plat/packet_inlines.h:34,
                 from ../platform/linux-dpdk/include-abi/odp/api/abi/packet.h:81,
                 from ../include/odp/api/packet.h:23,
                 from ../include/odp/api/spec/event.h:22,
                 from ../include/odp/api/event.h:22,
                 from ../include/odp/api/spec/queue.h:23,
                 from ../include/odp/api/queue.h:26,
                 from ../include/odp_api.h:42,
                 from ../helper/include/odp/helper/ip.h:20,
                 from ip.c:9:
/home/nnn/dev/dpdk.git/lib/librte_eal/common/include/rte_eal.h:87:35: error: 'RTE_MAX_LCORE' undeclared here (not in a function)
  enum rte_lcore_role_t lcore_role[RTE_MAX_LCORE]; /**< State of cores. */

```

**Comment by lumag** [comment]
PR updated

**Comment by matiaselo** [comment]
> Strange, why wasn't this caught by Travis? '--disable-abi-compat' build succeeded there.
I will update the patchset anyway.

Wondering the same thing, but it works now with the latest PR revision.

**Comment by muvarov** [comment]
Merged.
